name: Deploy

on:
  push:
    branches: main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            HOSTNAME: ${{ secrets.HOST_DNS }}
            USER_NAME: ${{ secrets.USERNAME }}
            TARGET: ${{ secrets.TARGET_DIR }}
        run: |
          touch EPSI2023_G3.pem
          echo ${PRIVATE_KEY} > EPSI2023_G3.pem && chmod 777 EPSI2023_G3.pem
          scp -i EPSI2023_G3.pem sample2.war ${USER_NAME}@${HOSTNAME}:${TARGET}
          ls
