name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./sample2.war
          host: ${{ secrets.HOST_DNS }}
          remote: ${{ secrets.TARGET_DIR }}
          port: ${{ secrets.DEPLOY_PORT }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
